export enum AuditKindsEnum {
  'first-contentful-paint' = 'first-contentful-paint',
  'first-meaningful-paint' = 'first-meaningful-paint',
  'speed-index' = 'speed-index',
  'screenshot-thumbnails' = 'screenshot-thumbnails',
  'final-screenshot' = 'final-screenshot',
  'estimated-input-latency' = 'estimated-input-latency',
  'total-blocking-time' = 'total-blocking-time',
  'max-potential-fid' = 'max-potential-fid',
  'time-to-first-byte' = 'time-to-first-byte',
  'first-cpu-idle' = 'first-cpu-idle',
  'interactive' = 'interactive',
  'user-timings' = 'user-timings',
  'critical-request-chains' = 'critical-request-chains',
  'redirects' = 'redirects',
  'mainthread-work-breakdown' = 'mainthread-work-breakdown',
  'bootup-time' = 'bootup-time',
  'uses-rel-preload' = 'uses-rel-preload',
  'uses-rel-preconnect' = 'uses-rel-preconnect',
  'font-display' = 'font-display',
  'diagnostics' = 'diagnostics',
  'network-requests' = 'network-requests',
  'network-rtt' = 'network-rtt',
  'network-server-latency' = 'network-server-latency',
  'main-thread-tasks' = 'main-thread-tasks',
  'metrics' = 'metrics',
  'performance-budget' = 'performance-budget',
  'resource-summary' = 'resource-summary',
  'third-party-summary' = 'third-party-summary',
  'uses-long-cache-ttl' = 'uses-long-cache-ttl',
  'total-byte-weight' = 'total-byte-weight',
  'offscreen-images' = 'offscreen-images',
  'render-blocking-resources' = 'render-blocking-resources',
  'unminified-css' = 'unminified-css',
  'unminified-javascript' = 'unminified-javascript',
  'unused-css-rules' = 'unused-css-rules',
  'uses-webp-images' = 'uses-webp-images',
  'uses-optimized-images' = 'uses-optimized-images',
  'uses-text-compression' = 'uses-text-compression',
  'uses-responsive-images' = 'uses-responsive-images',
  'efficient-animated-content' = 'efficient-animated-content',
  'dom-size' = 'dom-size',
}

export enum CategoryKindsEnum {
  'performance' = 'performance',
}
